step0_repl: src/step0_repl/step0_repl.go
	go build src/step0_repl/*.go

step1_read_print: src/step1_read_print/*.go
	go build -o step1_read_print src/step1_read_print/*.go

step2_eval: src/step2_eval/*.go
	go build -o step2_eval src/step2_eval/*.go
