step0_repl: src/step0_repl/step0_repl.go
	go build src/step0_repl/*.go

step1_read_print: src/step8_macros/*.go
	go build -o step1_read_print src/step8_macros/*.go

step2_eval: src/step8_macros/*.go
	go build -o step2_eval src/step8_macros/*.go

step3_env: src/step3_env/*.go
	go build -o step3_env src/step3_env/*.go

step4_if_fn_do: src/step8_macros/*.go
	go build -o step4_if_fn_do src/step8_macros/*.go

step5_tco: src/step5_tco/*.go
	go build -o step5_tco src/step5_tco/*.go

step6_file: src/step8_macros/*.go
	go build -o step6_file src/step8_macros/*.go

step7_quote: src/step8_macros/*.go
	go build -o step7_quote src/step8_macros/*.go

step8_macros: src/step8_macros/*.go
	go build -o step8_macros src/step8_macros/*.go

step9_try: src/step9_try/*.go
	go build -o step9_try src/step9_try/*.go