step0_repl: src/step0_repl/step0_repl.go
	go build src/step0_repl/*.go

step1_read_print: src/step1_read_print/*.go
	go build -o step1_read_print src/step1_read_print/*.go

step2_eval: src/step2_eval/*.go
	go build -o step2_eval src/step2_eval/*.go

step3_env: src/step3_env/*.go
	go build -o step3_env src/step3_env/*.go

step4_if_fn_do: src/step4_if_fn_do/*.go
	go build -o step4_if_fn_do src/step4_if_fn_do/*.go

step5_tco: src/step5_tco/*.go
	go build -o step5_tco src/step5_tco/*.go

step6_file: src/step6_file/*.go
	go build -o step6_file src/step6_file/*.go

step7_quote: src/step7_quote/*.go
	go build -o step7_quote src/step7_quote/*.go
