zig-out/bin/step0_repl: src/step0_repl/*.zig
	zig build

step1_read_print: src/step8_macros/*.go
	go build -o step1_read_print src/step8_macros/*.go

step2_eval: src/step9_try/*.go
	go build -o step2_eval src/step9_try/*.go

step3_env: src/step9_try/*.go
	go build -o step3_env src/step9_try/*.go

step4_if_fn_do: src/step8_macros/*.go
	go build -o step4_if_fn_do src/step8_macros/*.go

step5_tco: src/step5_tco/*.go
	go build -o step5_tco src/step5_tco/*.go

step6_file: src/step8_macros/*.go
	go build -o step6_file src/step8_macros/*.go

step7_quote: src/step9_try/*.go
	go build -o step7_quote src/step9_try/*.go

step8_macros: src/step8_macros/*.go
	go build -o step8_macros src/step8_macros/*.go

step9_try: src/step9_try/*.go
	go build -o step9_try src/step9_try/*.go

stepA_mal: src/stepA_mal/*.go
	go build -o stepA_mal src/stepA_mal/*.go
	
